"""add summary to notes

Revision ID: 259b5dd3d9d6
Revises: 8fbaab022864
Create Date: 2026-03-26 18:46:06.455530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259b5dd3d9d6'
down_revision: Union[str, Sequence[str], None] = '8fbaab022864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'summary')
    # ### end Alembic commands ###
